# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/appstudio-controller"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/backend-shared"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/cluster-agent"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/tests-e2e"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/utilities/db-migration"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/utilities/init-container"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/utilities/load-test"
    schedule:
      interval: "daily"
